service: chaining # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: '*'

functions:
  hello:
    handler: handler.hello
  hola:
    handler: handler.hola
