
service: chaining # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "*"


functions:
  hello:
    handler: handler.hello
  hola:
    handler: handler.hola